---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: workstations
  become: true
  tasks: 
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root 
      
- hosts: web_server 
  become: true
  tasks:

    - name: install httpd and php package
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest

    - name: copy default html file for site
      tags: apache,centos,httpd
      copy: 
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db_server
  become: yes
  tasks:

    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      dnf: 
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"
  
